webdev/tasks/urls.py
from django.urls import path
from webdev.tasks import views

app_name ='tasks'

urlpatterns=[
    path('', views.home, name='home'),
    path('<int:task_id>', views.detail, name='detail'),
    path('delete/<int:task_id>', views.delete, name='delete'),
]

webdev/urls.py
from django.contrib import admin
from django.urls import include, path
from webdev.home_view import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('tasks/', include('webdev.tasks.urls'))
]

webdev/tasks/models.py
# Create your models here.
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=128)
    done = models.BooleanField(default=False)

webdev/tasks/forms.py
from django.forms import ModelForm

from webdev.tasks.models import Task


class NewTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name']


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'done']

webdev/tasks/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from webdev.tasks.forms import NewTaskForm, TaskForm
from webdev.tasks.models import Task

def home(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('tasks:home'))
        else:
            pending_tasks = Task.objects.filter(done=False).all()
            tasks_done = Task.objects.filter(done=True).all()
            return render(
                request, 'tasks/home.html',
                {
                    'form': form,
                    'pending_tasks': pending_tasks,
                    'tasks_done': tasks_done,
                },
                status=400)
    pending_tasks = Task.objects.filter(done=False).all()
    tasks_done = Task.objects.filter(done=True).all()
    return render(request, 'tasks/home.html',
                  {
                      'pending_tasks': pending_tasks,
                      'tasks_done': tasks_done,
                  })

def detail(request, task_id):
    if request.method=='POST':
        task = Task.objects.get(id=task_id)
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
    return HttpResponseRedirect(reverse('tasks:home'))


def delete(request, task_id):
    if request.method == 'POST':
         Task.objects.filter(id=task_id).delete()
    return HttpResponseRedirect(reverse('tasks:home'))

webdev/tasks/templates/tasks/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Tasks List Demo App</title>
        <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <h1 class="mt-5">Task List Demo</h1>

                    <form action="{% url 'tasks:home' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Describe your task"
                                   aria-label="Describe your task" aria-describedby="button-addon2" name="name">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary" id="button-addon2">Save</button>
                            </div>
                        </div>
                        <small class="form-text text-muted">{{ form.name.errors }}</small>
                    </form>

                    <h2 class="mt-5">Pending Tasks</h2>

                    {% for task in pending_tasks %}
                        <form action="{% url 'tasks:detail' task_id=task.id %}" method="post">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Describe your task" required="required"
                                       aria-label="Describe your task" name="name" value="{{ task.name }}">
                                <input type="hidden" value="checked" name="done">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-success">Mask as done</button>
                                </div>
                            </div>
                        </form>
                    {% endfor %}

                    <h2 class="mt-5">Tasks Finished</h2>

                    {% for task in tasks_done %}
                        <div class="row">
                            <div class="col-2">
                                <form action="{% url 'tasks:delete' task_id=task.id %}" method="post">
                                    {% csrf_token %}
                                    <div class="input-group mb-3">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="col-10">
                                <form action="{% url 'tasks:detail' task_id=task.id %}" method="post">
                                    {% csrf_token %}
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder="Describe your task" required="required"
                                               aria-label="Describe your task" name="name" value="{{ task.name }}">

                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-warning">Mask as pendent</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </body>
</html>